url: http://musiqueroyale.com

plugins:
#- jekyll-minifier
#- jekyll-sitemap

encoding: utf-8

future: true

exclude:
- CNAME
- README.md
- /_site/*
- /archive
- instructions.txt

include:
- /.htaccess



timezone: America/Halifax

#collections_dir:
#- collections

collections:
  artists:
    output: false
    permalink: /artist/:path/
  venues:
    output: false
    permalink: /venue/:path/
  events:
    output: true
    permalink: /event/:path/


defaults:
  - scope:
      path: ''
      type: events
    values:
      layout: event
